### ISSUE TITLE
How to properly detach?

### ISSUE THREAD

**Issue by Krenair** [vstinner/python-ptrace#36]
I can't figure out how to detach from a process, preventing me from later re-attaching:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ptrace.debugger
>>> debugger = ptrace.debugger.PtraceDebugger()
>>> process = debugger.addProcess(485, False)
>>> process.readBytes(0x00673364, 4)
';\xaa4\x1d'
>>> debugger.deleteProcess(process)
>>> debugger.quit()
>>> process = debugger.addProcess(485, False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ptrace/debugger/debugger.py", line 74, in addProcess
    process = PtraceProcess(self, pid, is_attached, parent=parent)
  File "/usr/lib/python2.7/dist-packages/ptrace/debugger/process.py", line 167, in __init__
    self.attach()
  File "/usr/lib/python2.7/dist-packages/ptrace/debugger/process.py", line 184, in attach
    ptrace_attach(self.pid)
  File "/usr/lib/python2.7/dist-packages/ptrace/binding/func.py", line 157, in ptrace_attach
    ptrace(PTRACE_ATTACH, pid)
  File "/usr/lib/python2.7/dist-packages/ptrace/binding/func.py", line 150, in ptrace
    raise PtraceError(message, errno=errno, pid=pid)
ptrace.error.PtraceError: ptrace(cmd=16, pid=485, 0, 0) error #1: Operation not permitted

```

**Comment by haypo** [comment]
Hi,

I see different flaws in you code and in python-ptrace:

* You must call process.detatch() instead of debugger.deleteProcess(process)
* process.detach() doesn't call ptrace_detach() but ptrace_cont() if addProcess() was called with is_attached=False

IMHO the bug is in the detach() method: it should call ptrace_detach().

This use case is not properly supported and the module must be fixed for that. Would you mind to modify the code for that? (Propose a pull request.)

**Comment by Krenair** [comment]
Thanks. I've confirmed that after making the change (`debugger.deleteProcess(process)` -> `process.detach()`) it still doesn't appear to detach properly. Your idea about is_attached/was_attached appears correct. I'll try it out.
